// lib/schema.ts
// Helpers for generating JSON-LD schema markup

import { SPONSOR_NAME, SPONSOR_URL, SPONSOR_ORG_ID } from "./sponsor";

export interface SchemaMarkup {
  "@context": string;
  "@type": string;
  [key: string]: unknown;
}

const SUFFIX = " — The Dime Podcast";

// Cuts to the last whole word before maxLength and appends an ellipsis,
// so titles/descriptions never end mid-word — used everywhere a
// dynamic (RSS/YouTube/AI-generated) string feeds a meta tag.
export function truncateDescription(text: string | undefined | null, maxLength = 155): string {
  if (!text) return "";
  const trimmed = text.trim();
  if (trimmed.length <= maxLength) return trimmed;
  const cut = trimmed.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
}

export function truncateTitle(text: string | undefined | null, maxLength = 60): string {
  if (!text) return "";
  const trimmed = text.trim();
  if (trimmed.length <= maxLength) return trimmed;
  const cut = trimmed.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
}

// Full `<title>` value: truncates the page-specific part, then appends the
// site suffix — used by SeoHead so the suffix never itself pushes a title
// over the limit.
export function buildPageTitle(pageTitle: string, maxLength = 60): string {
  const budget = maxLength - SUFFIX.length;
  return truncateTitle(pageTitle, budget > 0 ? budget : maxLength) + SUFFIX;
}

export function createPodcastEpisodeSchema(
  episode: {
    title: string;
    description: string;
    slug: string;
    dateISO: string;
    duration: string;
    durationISO?: string;
    audioUrl: string;
    id: string;
  },
  siteUrl: string = "https://www.dimepodcast.com",
  options: {
    aiGenerated?: boolean;
    entities?: { companies: string[]; people: string[] };
    guest?: { name: string; company?: string; companyUrl?: string };
  } = {}
): SchemaMarkup {
  const schema: SchemaMarkup = {
    "@context": "https://schema.org",
    "@type": "PodcastEpisode",
    name: episode.title,
    description: episode.description,
    url: `${siteUrl}/episodes/${episode.slug}`,
    datePublished: episode.dateISO,
    author: {
      "@type": "Person",
      name: "Bryan Fields",
    },
    audio: {
      "@type": "AudioObject",
      url: episode.audioUrl,
      duration: episode.durationISO || episode.duration,
    },
    potentialAction: {
      "@type": "ListenAction",
      target: `https://player.simplecast.com/${episode.id}`,
    },
    // Reference (not a full definition) of Newton's Organization node. The
    // @id is the exact one the Newton site emits for itself, so the two
    // sites' JSON-LD resolve to one entity rather than two look-alikes.
    // Mirrors the visible sponsor slot on the page (SponsorSlot.js).
    sponsor: {
      "@type": "Organization",
      "@id": SPONSOR_ORG_ID,
      name: SPONSOR_NAME,
      url: SPONSOR_URL,
    },
  };

  if (options.aiGenerated) {
    schema.disclaimer =
      "This page includes a transcript and summary sections generated by AI from the episode audio; they may contain errors.";
  }

  // The guest as a structured entity — previously only the host was
  // represented, leaving the guest (the actual search-query-worthy name)
  // invisible to entity-based search/LLM grounding.
  if (options.guest?.name) {
    schema.contributor = personNode(options.guest.name, options.guest.company, options.guest.companyUrl);
  }

  // Entity-level signal for search/LLM retrieval — other companies and
  // people actually named in the conversation, beyond the guest.
  const mentions = [
    ...(options.entities?.companies || []).map((name) => ({ "@type": "Organization", name })),
    ...(options.entities?.people || []).map((name) => ({ "@type": "Person", name })),
  ];
  if (mentions.length) {
    schema.mentions = mentions;
  }

  return schema;
}

// Nested Person fragment (no @context — only for embedding inside another
// schema node, e.g. PodcastEpisode.contributor).
function personNode(name: string, company?: string, companyUrl?: string): Record<string, unknown> {
  const node: Record<string, unknown> = { "@type": "Person", name };
  if (company) {
    node.worksFor = {
      "@type": "Organization",
      name: company,
      ...(companyUrl ? { url: companyUrl } : {}),
    };
  }
  return node;
}

// Standalone Person schema, for guest entity pages.
export function createPersonSchema(person: {
  name: string;
  company?: string;
  companyUrl?: string;
}): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    ...personNode(person.name, person.company, person.companyUrl),
  } as SchemaMarkup;
}

export function createBreadcrumbSchema(
  items: { name: string; url: string }[]
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

// FAQPage schema for the AI-generated Q&A pairs on an episode page — this
// is the structured-data type most likely to get lifted directly into
// Google AI Overviews and LLM answer engines.
export function createFAQSchema(
  faq: { question: string; answer: string }[]
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faq.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}

// Article schema for a First Principles newsletter edition. Unlike the
// episode/video schemas, these are human-written, so there is deliberately
// no `disclaimer` field and the author is a Person rather than the show.
//
// `isPartOf` groups all 31+ editions under one CreativeWorkSeries so search
// and LLM crawlers read them as a named publication rather than 31 loose
// posts, and `about` points at the episode the edition analyses — the same
// relationship the visible cross-link expresses, restated for machines.
export function createArticleSchema(
  edition: {
    title: string;
    description: string;
    slug: string;
    date: string;
    episodeSlug?: string;
    wordCount?: number;
  },
  siteUrl: string = "https://www.dimepodcast.com"
): SchemaMarkup {
  const url = `${siteUrl}/newsletter/${edition.slug}`;
  const schema: SchemaMarkup = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: edition.title,
    description: edition.description,
    url,
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    datePublished: edition.date,
    author: {
      "@type": "Person",
      name: "Bryan Fields",
    },
    publisher: {
      "@type": "Organization",
      name: "The Dime Podcast",
      url: siteUrl,
    },
    isPartOf: {
      "@type": "CreativeWorkSeries",
      name: "First Principles",
      url: `${siteUrl}/newsletter`,
    },
  };

  if (edition.wordCount) {
    schema.wordCount = edition.wordCount;
  }

  if (edition.episodeSlug) {
    schema.about = {
      "@type": "PodcastEpisode",
      url: `${siteUrl}/episodes/${edition.episodeSlug}`,
    };
  }

  return schema;
}

export function createVideoObjectSchema(
  video: {
    title: string;
    description: string;
    slug: string;
    thumbnail: string;
    publishedAt: string;
    duration: string;
    durationISO?: string;
    id: string;
  },
  siteUrl: string = "https://www.dimepodcast.com"
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title,
    description: video.description,
    url: `${siteUrl}/videos/${video.slug}`,
    thumbnailUrl: video.thumbnail,
    uploadDate: video.publishedAt,
    duration: video.durationISO || video.duration,
    embedUrl: `https://www.youtube.com/embed/${video.id}`,
  };
}

export function createPodcastSchema(
  siteUrl: string = "https://www.dimepodcast.com",
  rating?: { value: number; count: number }
): SchemaMarkup {
  const schema: SchemaMarkup = {
    "@context": "https://schema.org",
    "@type": "PodcastSeries",
    name: "The Dime",
    url: siteUrl,
    description: "Cannabis business intelligence. Strategy conversations for operators, not observers.",
    author: {
      "@type": "Organization",
      name: "The Dime Podcast",
    },
    image: `${siteUrl}/logo.png`,
  };

  if (rating) {
    schema.aggregateRating = {
      "@type": "AggregateRating",
      ratingValue: rating.value,
      ratingCount: rating.count,
    };
  }

  return schema;
}

export function createOrganizationSchema(
  siteUrl: string = "https://www.dimepodcast.com"
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "The Dime Podcast",
    url: siteUrl,
    description: "Cannabis business intelligence.",
    sameAs: ["https://twitter.com/thedime_cannabis"],
  };
}

// WebSite node with a SearchAction — the standard low-effort schema for
// sitelinks-search-box eligibility in Google SERPs.
export function createWebsiteSchema(
  siteUrl: string = "https://www.dimepodcast.com"
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "The Dime Podcast",
    url: siteUrl,
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteUrl}/episodes?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
}

// CollectionPage/ItemList schema for archive/hub pages (episodes, videos,
// topics index) that otherwise carry zero structured data.
export function createCollectionPageSchema(
  page: { name: string; description: string; url: string },
  items: { name: string; url: string }[]
): SchemaMarkup {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: page.name,
    description: page.description,
    url: page.url,
    mainEntity: {
      "@type": "ItemList",
      itemListElement: items.map((item, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: item.name,
        url: item.url,
      })),
    },
  };
}
