// lib/videoEpisodeMap.ts
// Cross-links episode pages and video pages. The forward map (episode slug ->
// YouTube video IDs) is written by bot/video_episode_map.py to
// content/video-episode-map.json; this module also builds the reverse index
// (video ID -> episode slug) in memory, since the source JSON is
// episode-keyed and a video page needs to look the other direction.
//
// The map file is generated by a separate pipeline and may not exist yet in
// a given checkout — every lookup here degrades to an empty result rather
// than throwing.

import fs from "fs";
import path from "path";

export type VideoEpisodeMap = Record<string, string[]>;

const MAP_FILE = path.join(process.cwd(), "content", "video-episode-map.json");

function loadVideoEpisodeMap(): VideoEpisodeMap {
  try {
    if (!fs.existsSync(MAP_FILE)) return {};
    const raw = fs.readFileSync(MAP_FILE, "utf-8");
    return JSON.parse(raw) as VideoEpisodeMap;
  } catch (error) {
    console.error("Error reading video-episode-map.json:", error);
    return {};
  }
}

// Slug -> video IDs, as read from disk.
export function getAllVideoEpisodeMap(): VideoEpisodeMap {
  return loadVideoEpisodeMap();
}

// Episode slug -> its YouTube video IDs (empty array if none, or if the map
// hasn't been generated yet).
export function getVideoIdsForEpisode(slug: string): string[] {
  const map = loadVideoEpisodeMap();
  return map[slug] ?? [];
}

// Video ID -> episode slug, built by inverting the forward map since the
// source JSON is episode-keyed.
function buildReverseIndex(map: VideoEpisodeMap): Record<string, string> {
  const reverse: Record<string, string> = {};
  for (const [slug, videoIds] of Object.entries(map)) {
    for (const videoId of videoIds) {
      reverse[videoId] = slug;
    }
  }
  return reverse;
}

export function getEpisodeSlugForVideo(videoId: string): string | undefined {
  const map = loadVideoEpisodeMap();
  return buildReverseIndex(map)[videoId];
}
