// Visible disclosure label placed above any AI-generated content block
// (transcript, takeaways, FAQ, quotes). Keep this unambiguous — it should
// be obvious to a reader that this section wasn't written by the hosts.

export default function AIDisclosure({
  children = 'Generated by AI from the episode audio — may contain errors',
}) {
  return (
    <div
      className="mono"
      style={{
        fontSize: '10px',
        fontWeight: 700,
        letterSpacing: '.08em',
        textTransform: 'uppercase',
        color: 'var(--text-muted)',
        border: '1px solid var(--border-default)',
        borderRadius: '4px',
        padding: '6px 12px',
        display: 'inline-block',
        marginBottom: '16px',
      }}
    >
      AI-Generated · {children}
    </div>
  );
}
