"""
Email client for sending research documents via Gmail SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from pathlib import Path
from config import config


class EmailClient:
    """Client for sending emails with attachments via SMTP."""

    def __init__(self):
        self.host = config.EMAIL_HOST
        self.port = config.EMAIL_PORT
        self.username = config.EMAIL_USERNAME
        self.password = config.EMAIL_PASSWORD
        self.from_email = config.EMAIL_FROM
        self.to_email = config.EMAIL_TO

    def send_research_document(
        self, guest_name: str, document_path: str
    ) -> bool:
        """
        Send research document via email.

        Args:
            guest_name: Name of the guest
            document_path: Path to the .docx file

        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            print(f"Sending email to {self.to_email}...")

            # Create message
            msg = MIMEMultipart()
            msg["From"] = self.from_email
            msg["To"] = self.to_email
            msg["Subject"] = f"Guest Research: {guest_name}"

            # Email body
            body = self._create_email_body(guest_name)
            msg.attach(MIMEText(body, "plain"))

            # Attach document
            self._attach_document(msg, document_path)

            # Send email via SMTP
            with smtplib.SMTP(self.host, self.port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)

            print(f"Email sent successfully to {self.to_email}")
            return True

        except smtplib.SMTPAuthenticationError:
            print("Error: SMTP authentication failed. Check email credentials.")
            return False
        except smtplib.SMTPException as e:
            print(f"SMTP error: {e}")
            return False
        except Exception as e:
            print(f"Error sending email: {e}")
            return False

    def _create_email_body(self, guest_name: str) -> str:
        """
        Create email body text.

        Args:
            guest_name: Name of the guest

        Returns:
            Email body text
        """
        return f"""Hello,

Please find attached the AI-generated research document for {guest_name}.

This research was automatically generated by The Dime Podcast automation system.

Best regards,
The Dime Podcast Research Bot
"""

    def _attach_document(self, msg: MIMEMultipart, document_path: str) -> None:
        """
        Attach Word document to email.

        Args:
            msg: Email message object
            document_path: Path to document file
        """
        path = Path(document_path)

        if not path.exists():
            raise FileNotFoundError(f"Document not found: {document_path}")

        with open(path, "rb") as file:
            attachment = MIMEApplication(file.read(), _subtype="docx")
            attachment.add_header(
                "Content-Disposition", "attachment", filename=path.name
            )
            msg.attach(attachment)

    def validate_smtp_connection(self) -> bool:
        """
        Validate SMTP connection and credentials.

        Returns:
            True if connection successful, False otherwise
        """
        try:
            with smtplib.SMTP(self.host, self.port, timeout=10) as server:
                server.starttls()
                server.login(self.username, self.password)
            print("SMTP connection validated successfully")
            return True
        except smtplib.SMTPAuthenticationError:
            print("Error: SMTP authentication failed")
            return False
        except Exception as e:
            print(f"Error validating SMTP connection: {e}")
            return False
